from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.gridlayout import GridLayout
from kivy.properties import ObjectProperty
#from kivy.core.window import Window
from kivy.uix.label import Label

import random

#Window.size = (480, 960)


phraseslovar = ['How are you?', 'Can I help you?', 'Where are you from?',
              'I would like to make\na reservation',  'How is it going?',
			 'How`s life?',
			 'How are things?',
			 'Long time no see!',
			 'What are you up to?',
			 'What have you been up to?',
			 'See you soon!',
			 'See you later!',
			 'Till next time!',
			 'Good luck!',
			 'Take care!',
			 'Talk to you later!',
			 'Until we meet again!',
			 'Have a nice day!',
			 'Have a good weekend',
			 'Have a safe trip',
			 'Say hi to …',
			 'Send my love to …',
			 'In short / in brief',
			 'In a word',
			 'As far / as to',
			 'Not to mention',
			 'First of all/ above all',
			 'What’s more',
			 'By the way',
			 'After all',
			 'Just for the record',
			 'And so on and so forth',
			 'If I’m not mistaken',
			 'In other words',
			 'On the contrary',
			 'The thing is',
			 'So as to / so that',
			 'Either way',
			 'As a rule',
			 'As well as',
			 'All the same',
			 'On one hand',
			 'On the other hand',
			 'Such as',
			 'As I said before',
			 'Believe it or not, but',
			 'If I remember rightly/\nIf I recall correctly',
			 'Perhaps',
			 'Of course / Sure',
			 'Definitely',
			 'Absolutely',
			 'Naturally',
			 'Probably',
			 'You are right',
			 'It can hardly be so',
			 'Very well',
			 'Most likely',
			 'Most unlikely',
			 'Not a bit',
			 'I believe so / suppose so',
			 'I doubt it',
			 'No way',
			 'Exactly so',
			 'Quite so',
			 'I agree with you',
			 'I am afraid you are wrong',
			 'I’m afraid so',
			 'I’m not sure',
			 'I don’t think so',
			 'In a way/to a certain extent',
			 'No doubt',
			 'I’m in / I’m game',
			 'I think I’ll pass',
			 'Deal!',
			 'It’s a great idea!',
			 'Not a very good idea',
			 'I`m looking forward to it',
			 'I’m so sorry!',
			 'I beg your pardon!',
			 'I’m sorry, I can’t.',
			 'Sorry, I meant well.',
			 'It’s very kind of you!',
			 'Thank you anyway!',
			 'Thank you in advance!',
			 'Don’t mention it!',
			 'May I help you?',
			 'No problem / that’s ok!',
			 'Don’t worry about it!',
			 'This way, please!',
			 'After you!',
			 'What’s the matter?',
			 'What’s going on?/What’s\nhappening?',
			 'What’s the trouble?',
			 'What’s happened?',
			 'How was it?',
			 'Did I get you right?',
			 'Don’t take it to heart.',
			 'I didn’t catch the last word.',
			 'Sorry, I wasn’t listening.',
			 'It doesn’t matter.',
			 'It is new to me.',
			 'Let us hope for the best.',
			 'May I ask you a question?',
			 'Next time lucky!',
			 'Oh, that. That explains it.',
			 'Say it again, please.',
			 'So that’s where the trouble\nlies!',
			 'Things happen.',
			 'What do you mean?',
			 'Where were we?',
			 'You were saying?',
			 'I’m sorry, I didn’t catch\nyou.',
			 'Lucky you!',
			 'Good for you!',
			 'I’m so happy for you!',
			 'What do you know!',
			 'Hello',
			 'Hi',
			 'Good morning',
			 'Good afternoon',
			 'Good evening',
			 'Goodbye',
			 'Bye',
			 'Good night',
			 'See you',
			 'Have a nice day',
			 'Please',
			 'Thank you (или Thanks)',
			 'Thank you very much',
			 'You`re welcome',
			 'Don`t mention it',
			 'Not at all',
			 'I’m sorry (или Sorry)',
			 'Excuse me',
			 'No problem',
			 'It`s ok или That`s ok',
			 'Don`t worry about it',
			 'Do you speak English?',
			 'I don`t speak English',
			 'I speak a little English',
			 'Please speak more slowly',
			 'Could you please repeat that?',
			 'Could you please spell that?',
			 'How do you say ... in\nEnglish?',
			 'How do you spell that?',
			 'How do you pronounce this\nword?',
			 'I understand',
			 'I don`t understand',
			 'Could you tell me how to\nget to the ...?',
			 'Do you know where the .. is?',
			 'How far is the…?',
			 'airport',
			 'train station',
			 'bus station',
			 'Can you show me on the map?',
			 'I`m looking for this address',
			 'It`s this way',
			 'It`s that way',
			 'You`re going the wrong way',
			 'Take this road',
			 'Turn left',
			 'Turn right',
			 'Go straight ahead',
			 'Take the first turn on the left',
			 'Take the second turn on\nthe right',
			 'Turn left at the crossroads',
			 'Continue straight ahead',
			 'Continue past the post office',
			 'You`ll pass a park on\nyour left',
			 'Keep going for another…',
			 'two hundred yards',
			 'hundred metres',
			 'half-mile',
			 'kilometre',
			 'It`ll be…',
			 'on your left',
			 'on your right',
			 'straight ahead of you',
			 'What`s this?',
			 'What`s this called?',
			 'Have you got a minute?',
			 'Can you help me?',
			 'May I borrow your pen?',
			 'May I use your phone?',
			 'Entrance',
			 'Exit',
			 'Emergency exit',
			 'Push',
			 'Pull',
			 'WC',
			 'Out of order',
			 'No smoking',
			 'Private',
			 'No entry',
			 'Help!',
			 'Be careful!',
			 'Look out! или watch out!',
			 'Is anything wrong?',
			 'What`s the matter?',
			 'Is everything ok?',
			 'What`s going on?',
			 'What happened?',
			 'Are you ok?',
			 'Is everyone ok?',
			 'I need help',
			 'I need a doctor',
			 'Call an ambulance!',
			 'There`s been an accident',
			 'I`ve cut myself',
			 'I`ve burnt myself',
			 'I’ve hurt my…',
			 'Call the police!',
			 'I`ve been mugged',
			 'I`ve been attacked',
			 'Fire!',
			 'Call the fire brigade!',
			 'There`s a fire',
			 'The building is on fire',
			 'I`m lost',
			 'We`re lost',
			 'I can`t find my…',
			 'I`ve lost my…',
			 'Please leave me alone',
			 'Go away',
			 'I’ll call the police',
			 'I think',
			 'It seems to me',
			 'In my opinion',
			 'To be honest',
			 'To tell you\nthe truth',
			 'To my mind',
			 'Okay',
			 'Deal',
			 'I agree (with you)',
			 'Sure \ Of course',
			 'Right \ That’s right',
			 'Exactly \ Absolutely',
			 'I couldn’t (can’t) agree more',
			 'Why not?',
			 'I guess so',
			 'I don’t agree (with you)',
			 'Absolutely not\nOf course not',
			 'Nothing of the kind',
			 'I don’t think so',
			 'Are you kidding?',
			 'You must be kidding',
			 'Would you like…?',
			 'Do you want…?',
			 'How about…?',
			 'Can I offer you…?',
			 'Let’s',
			 'I recommend you …',
			 'You should …',
			 'Why don’t you …',
			 'If I were you …',
			 'You’d better\n(You had better) …',
			 'Well..',
			 'So…',
			 'As for me',
			 'As far as I remember…',
			 'As far as I know…',
			 'Actually…',
			 'By the way',
			 'The problem is that',
			 'The point is that',
			 'On the one hand…,\non the other hand…',
			 'Fortunately…',
			 'Unfortunately…',
			 'In my opinion…',
			 'It seems to me that…',
			 'I think \ I guess',
			 'Personally, I suppose …',
			 'Moreover, …',
			 'What’s worse is that',
			 'Briefly speaking …',
			 'Be careful',
			 'Be careful driving',
			 'Can you translate\nthis for me?',
			 'Chicago is very\ndifferent from Boston',
			 'Don`t worry',
			 'Everyone knows it',
			 'Everything is ready',
			 'Excellent',
			 'From time to time',
			 'Good idea',
			 'He likes it very much',
			 'Help!',
			 'He`s coming soon',
			 'He`s right',
			 'He`s very annoying',
			 'He`s very famous',
			 'How are you?',
			 'How`s work going?',
			 'Hurry!',
			 'I ate already',
			 'I can`t hear you',
			 'I`d like to go\nfor a walk',
			 'I don`t know how\nto use it',
			 'I don`t like him',
			 'I don`t like it',
			 'I don`t speak very well',
			 'I don`t understand',
			 'I don`t want it',
			 'I don`t want that',
			 'I don`t want to bother you',
			 'I feel good',
			 'If you need my help,\nplease let me know',
			 'I get off of work at 6',
			 'I have a headache',
			 'I hope you and your\nwife have a nice trip',
			 'I know',
			 'I like her',
			 'I`ll call you when\nI leave',
			 'I`ll come back later',
			 'I`ll take it',
			 'I`ll take you to the\nbus stop',
			 'I`ll pay',
			 'I lost my watch',
			 'I love you',
			 'I`m an American',
			 'I`m cleaning my room',
			 'I`m cold',
			 'I`m coming to pick you up',
			 'I`m going to leave',
			 'I`m good, and you?',
			 'I`m happy',
			 'I`m hungry',
			 'I`m married',
			 'I`m not busy',
			 'I`m not married',
			 'I`m not ready yet',
			 'I`m not sure',
			 'I`m sorry, we`re\nsold out',
			 'I`m thirsty',
			 'I`m very busy. I\ndon`t have time now',
			 'I need to change clothes',
			 'I need to go home',
			 'I only want a snack',
			 'Is Mr. Smith an American?',
			 'Is that enough?',
			 'I think it`s very good',
			 'I think it tastes good',
			 'I thought the clothes\nwere cheaper',
			 'It`s longer than 2 miles',
			 'I`ve been here for\ntwo days',
			 'I`ve heard Texas\nis a beautiful place',
			 'I`ve never seen\nthat before',
			 'I was about to leave the restaurant when my friends arrived',
			 'Just a little',
			 'Just a moment',
			 'Let me check',
			 'Let me think about it',
			 'Let`s go have a look',
			 'Let`s practice English',
			 'May I speak to Mrs.\nSmith please?',
			 'More than that',
			 'Never mind',
			 'Next time',
			 'No',
			 'Nonsense',
			 'No, thank you',
			 'Nothing else',
			 'Not recently',
			 'Not yet',
			 'Of course',
			 'Okay',
			 'Please fill out this form',
			 'Please take me to this\naddress',
			 'Please write it down',
			 'Really?',
			 'Right here',
			 'Right there',
			 'See you later',
			 'See you tomorrow',
			 'See you tonight',
			 'She`s pretty',
			 'Sorry to bother you',
			 'Stop!',
			 'Take a chance',
			 'Take it outside',
			 'Tell me',
			 'Thanks for everything',
			 'Thanks for your help',
			 'Thank you',
			 'Thank you miss',
			 'Thank you sir',
			 'Thank you very much',
			 'That looks great',
			 'That`s alright',
			 'That`s enough',
			 'That`s fine',
			 'That`s it',
			 'That smells bad',
			 'That`s not fair',
			 'That`s not right',
			 'That`s right',
			 'That`s too bad',
			 'That`s too many',
			 'That`s too much',
			 'The book is under the table',
			 'They`ll be right back',
			 'They`re the same',
			 'They`re very busy',
			 'This doesn`t work',
			 'This is very difficult',
			 'This is very important',
			 'Try it',
			 'Very good, thanks',
			 'We like it very much',
			 'Would you take a\nmessage please?',
			 'Yes, really',
			 'You`re beautiful',
			 'You`re very nice',
			 'You`re very smart',
			 'Your things are\nall here',
			 'Certainly!',
			 'Good afternoon',
			 'Good evening sir',
			 'Good Luck',
			 'Good morning',
			 'Great',
			 'Happy Birthday',
			 'Have a good trip',
			 'Nice to meet you']



dict500 = {'How are you?': 'Как дела?',
           'Can I help you?': 'Могу я вам помочь?',
           'Where are you from?': 'Вы откуда (территориально)?',
           'I would like to make\na reservation': 'Я бы хотел забронировать\n(гостиницу и т.п.)',
           'How is it going?': 'Как идут дела?',
			'How`s life?':	'Как жизнь?',
			'How are things?': 'Как оно?',
			'Long time no see!': 'Давно не виделись!',
			'What are you up to?':	'Чем занимаешься?',
			'What have you been up to?': 'Чем занимался все\nэто время?',
			'See you soon!': 'До скорого!',
			'See you later!': 'Увидимся позже!',
			'Till next time!': 'До следующего раза!',
			'Good luck!': 'Удачи!',
			'Take care!': 'Береги себя!',
			'Talk to you later!': 'Поговорим с тобой позже!',
			'Until we meet again!':	'До новой встречи!',
			'Have a nice day!': 'Хорошего дня!',
			'Have a good weekend':	'Хороших выходных',
			'Have a safe trip': 'Хорошей поездки',
			'Say hi to …':	'Передавай привет …',
			'Send my love to …': 'Передавай большой привет..\n(если речь идет о\nродственниках или\nблизких людях)',
			'In short / in brief':	'вкратце',
			'In a word': 'в двух словах',
			'As far / as to': 'что касается',
			'Not to mention': 'не говоря уже о',
			'First of all/ above all': 'прежде всего',
			'What’s more':	'кроме того',
			'By the way': 'кстати',
			'After all': 'в итоге; все-таки',
			'Just for the record':	'для справки;\nчтобы вы знали',
			'And so on and so forth': 'и так далее',
			'If I’m not mistaken':	'если я не ошибаюсь',
			'In other words': 'другими словами',
			'On the contrary': 'наоборот',
			'The thing is':	'дело в том, что',
			'So as to / so that': 'так чтобы',
			'Either way': 'так или иначе',
			'As a rule': 'обычно, как правило',
			'As well as': 'так же, как и',
			'All the same':	'без разницы',
			'On one hand': 'с одной стороны',
			'On the other hand': 'с другой стороны',
			'Such as': 'например',
			'As I said before': 'как я уже говорил',
			'Believe it or not, but': 'верите или нет, но',
			'If I remember rightly/\nIf I recall correctly': 'если я правильно помню',
			'Perhaps': 'Возможно, может быть',
			'Of course / Sure': 'Конечно',
			'Definitely': 'Определенно, непременно',
			'Absolutely': 'Безусловно',
			'Naturally': 'Естественно',
			'Probably': 'Вероятно',
			'You are right': 'Вы правы',
			'It can hardly be so': 'Вряд ли это так',
			'Very well': 'Очень хорошо',
			'Most likely': 'Скорее всего',
			'Most unlikely': 'Вряд ли',
			'Not a bit': 'Ничуть',
			'I believe so / suppose so': 'Полагаю, что это так',
			'I doubt it': 'Сомневаюсь',
			'No way': 'Ни за что, ни в коем случае',
			'Exactly so': 'Именно так',
			'Quite so': 'Вполне верно',
			'I agree with you': 'Я с вами согласен',
			'I am afraid you are wrong': 'Боюсь, что вы не правы',
			'I’m afraid so': 'Боюсь, что так',
			'I’m not sure':	'Не уверен',
			'I don’t think so': 'Я так не думаю; вряд ли',
			'In a way/to a certain extent': 'В каком-то смысле',
			'No doubt': 'Несомненно',
			'I’m in / I’m game': 'Я «за» (в ответ на\nпредложение куда-либо\nсходить или что-либо\nсделать)',
			'I think I’ll pass': 'Лучше без меня',
			'Deal!': 'Идет!',
			'It’s a great idea!': 'Отличная идея!',
			'Not a very good idea':	'Не самая хорошая идея',
			'I`m looking forward to it': 'Жду этого с нетерпением',
			'I’m so sorry!': 'Мне очень жаль!',
			'I beg your pardon!': 'Прошу прощения!',
			'I’m sorry, I can’t.': 'Простите, не могу.',
			'Sorry, I meant well.':	 'Извините, я хотел как лучше.',
			'It’s very kind of you!': 'Это очень мило\nс вашей стороны!',
			'Thank you anyway!': 'В любом случае, спасибо!',
			'Thank you in advance!': 'Спасибо заранее!',
			'Don’t mention it!': 'Не стоит благодарности!',
			'May I help you?': 'Могу ли я вам помочь?',
			'No problem / that’s ok!': 'Все в порядке!',
			'Don’t worry about it!': 'Не волнуйтесь об этом!',
			'This way, please!': 'Сюда, пожалуйста!',
			'After you!': 'После вас!',
			'What’s the matter?': 'В чем дело?',
			'What’s going on?/What’s\nhappening?': 'Что происходит?',
			'What’s the trouble?':	'В чем проблема?',
			'What’s happened?': 'Что случилось?',
			'How was it?':	'Ну как?\n(Как все прошло?)',
			'Did I get you right?': 'Я правильно вас понял?',
			'Don’t take it to heart.': 'Не принимайте\nблизко к сердцу.',
			'I didn’t catch the last word.': 'Я не понял последнее слово.',
			'Sorry, I wasn’t listening.': 'Извините, я прослушал.',
			'It doesn’t matter.': 'Это не имеет значения.',
			'It is new to me.': 'Это новость для меня.',
			'Let us hope for the best.': 'Будем надеяться на лучшее.',
			'May I ask you a question?': 'Можно задать вам вопрос?',
			'Next time lucky!': 'Повезет в следующий раз!',
			'Oh, that. That explains it.': 'Вот оно что,\nэто все объясняет.',
			'Say it again, please.': 'Повторите еще раз,\nпожалуйста.',
			'So that’s where the trouble\nlies!': 'Так вот в чем дело!',
			'Things happen.': 'Всякое бывает.',
			'What do you mean?': 'Что вы имеете в виду?',
			'Where were we?': 'На чем мы остановились?',
			'You were saying?': 'Вы что-то сказали?',
			'I’m sorry, I didn’t catch\nyou.': 'Простите, я не расслышал.',
			'Lucky you!': 'Вам повезло!',
			'Good for you!': 'Тем лучше для\nвас!(часто в ней\nподразумевается сарказм)',
			'I’m so happy for you!': 'Я так рад за вас!',
			'What do you know!': 'Кто бы мог подумать!',
			'Hello': 'Здравствуйте!',
			'Hi': 'Привет!',
			'Good morning': 'Доброе утро!',
			'Good afternoon': 'Добрый день!',
			'Good evening': 'Добрый вечер!',
			'Goodbye': 'До свидания!',
			'Bye':	'Пока!',
			'Good night': 'Спокойной ночи!',
			'See you': 'До встречи!',
			'Have a nice day': 'Хорошего дня!',
			'Please': 'пожалуйста',
			'Thank you (или Thanks)': 'спасибо',
			'Thank you very much':	'большое спасибо',
			'You`re welcome': 'пожалуйста (в\nответ на «спасибо»)',
			'Don`t mention it': 'не стоит благодарности',
			'Not at all': 'не за что',
			'I’m sorry (или Sorry)': 'извините',
			'Excuse me': 'простите(также\nиспользуется для\nпривлечения внимания)',
			'No problem': 'ничего страшного',
			'It`s ok или That`s ok': 'все в порядке',
			'Don`t worry about it': 'не стоит беспокойства',
			'Do you speak English?': 'Вы говорите по-английски?',
			'I don`t speak English': 'Я не говорю по-английски',
			'I speak a little English': 'Я немного говорю по-английски',
			'Please speak more slowly': 'Пожалуйста,\nговорите помедленнее',
			'Could you please repeat that?': 'Повторите, пожалуйста',
			'Could you please spell that?': 'Продиктуйте по\nбуквам, пожалуйста',
			'How do you say ... in\nEnglish?': 'Как по-английски будет ...?',
			'How do you spell that?': 'Как это пишется?',
			'How do you pronounce this\nword?': 'Как произносится это\nслово?',
			'I understand': 'Я понимаю',
			'I don`t understand': 'Я не понимаю',
			'Could you tell me how to\nget to the ...?': 'Вы не подскажете,\nкак добраться до…?',
			'Do you know where the .. is?': 'Вы не знаете,\nгде находится…?',
			'How far is the…?': 'Как далеко до…?',
			'airport': 'аэропорт',
			'train station': 'железнодорожный вокзал',
			'bus station':	'автобусная станция',
			'Can you show me on the map?': 'Вы можете показать\nмне на карте?',
			'I`m looking for this address': 'Я ищу этот адрес',
			'It`s this way': 'Это сюда',
			'It`s that way': 'Это туда',
			'You`re going the wrong way': 'Вы идете не в ту сторону',
			'Take this road': 'Следуйте по этой дороге',
			'Turn left': 'Поверните налево',
			'Turn right': 'Поверните направо',
			'Go straight ahead': 'Идите прямо',
			'Take the first turn on the left': 'Поверните на\nпервом повороте налево',
			'Take the second turn on\nthe right': 'Поверните на\nвтором повороте направо',
			'Turn left at the crossroads': 'На перекрестке\nповерните налево',
			'Continue straight ahead': 'Продолжайте идти\n(ехать) прямо',
			'Continue past the post office': 'Проходите (проезжайте)\nмимо здания почты',
			'You`ll pass a park on\nyour left': 'Слева будет парк',
			'Keep going for another…': 'Пройдите еще…',
			'two hundred yards': 'двести ярдов (1 ярд ≈ 0,9 м)',
			'hundred metres': 'сто метров',
			'half-mile': 'полмили (1 миля ≈ 1,6 км)',
			'kilometre': 'километр',
			'It`ll be…': 'Это будет ...',
			'on your left': 'слева',
			'on your right': 'справа',
			'straight ahead of you': 'прямо перед вами​',
			'What`s this?': 'Что это?',
			'What`s this called?':	'Как это называется?',
			'Have you got a minute?': 'У вас есть минутка?',
			'Can you help me?': 'Вы не могли бы мне помочь?',
			'May I borrow your pen?': 'Я могу позаимствовать\nвашу ручку?',
			'May I use your phone?': 'Я могу воспользоваться\nвашим телефоном?',
			'Entrance': 'Вход',
			'Exit': 'Выход',
			'Emergency exit': 'Запасной выход',
			'Push': 'От себя',
			'Pull': 'На себя',
			'WC': 'Tуалет',
			'Out of order': 'Не работает',
			'No smoking': 'Не курить',
			'Private': 'Частная собственность',
			'No entry': 'Вход воспрещен',
			'Help!': 'Помогите!',
			'Be careful!': 'Будьте осторожны!',
			'Look out! или watch out!': 'Осторожно!',
			'Is anything wrong?': 'Что-то не так?',
			'What`s the matter?': 'В чем дело?',
			'Is everything ok?': 'Все в порядке?',
			'What`s going on?': 'Что происходит?',
			'What happened?': 'Что случилось?',
			'Are you ok?':	'Вы в порядке?',
			'Is everyone ok?': 'Все целы?',
			'I need help': 'Мне нужна помощь',
			'I need a doctor': 'Мне нужен врач',
			'Call an ambulance!': 'Вызовите скорую!',
			'There`s been an accident': 'Произошел несчастный\nслучай',
			'I`ve cut myself': 'Я порезался',
			'I`ve burnt myself': 'Я обжегся',
			'I’ve hurt my…': 'Я повредил…',
			'Call the police!': 'Вызовите полицию!',
			'I`ve been mugged': 'Меня ограбили',
			'I`ve been attacked': 'На меня напали',
			'Fire!': 'Пожар!',
			'Call the fire brigade!': 'Вызовите пожарных!',
			'There`s a fire': 'Там пожар',
			'The building is on fire': 'Здание горит',
			'I`m lost': 'Я заблудился',
			'We`re lost': 'Мы заблудились',
			'I can`t find my…': 'Я не могу найти…',
			'I`ve lost my…': 'Я потерял…',
			'Please leave me alone': 'Пожалуйста,\nоставьте меня в покое',
			'Go away': 'Уйдите',
			'I’ll call the police': 'Я вызову полицию', 'I think': 'Я думаю',
			'It seems to me': 'Мне кажется',
			'In my opinion': 'По моему мнению',
			'To be honest': 'Честно говоря',
			'To tell you\nthe truth': 'По правде говоря',
			'To my mind': 'На мой взгляд',
			'Okay': 'Окей, хорошо',
			'Deal': 'Договорились',
			'I agree (with you)': 'Я согласен (с вами)',
			'Sure \ Of course': 'Конечно',
			'Right \ That’s right': 'Верно',
			'Exactly \ Absolutely': 'Точно',
			'I couldn’t (can’t) agree more': 'Не могу не согласиться',
			'Why not?': 'Почему бы и нет?',
			'I guess so': 'Думаю, да',
			'I don’t agree (with you)': 'Я не согласен (с вами)',
			'Absolutely not\nOf course not': 'Конечно, нет',
			'Nothing of the kind': 'Ничего подобного',
			'I don’t think so': 'Я так не думаю',
			'Are you kidding?': 'Ты шутишь?',
			'You must be kidding': 'Ты, наверное, шутишь',
			'Would you like…?': 'Не желаете ли вы…?',
			'Do you want…?': 'Ты хочешь…?',
			'How about…?': 'Как насчет…?',
			'Can I offer you…?': 'Могу я предложить вам…?',
			'Let’s': '…Давай…',
			'I recommend you …': 'Я рекомендую вам …',
			'You should …': 'Вам следует …',
			'Why don’t you …': 'Почему бы вам не …',
			'If I were you …': 'Я бы на вашем месте …',
			'You’d better\n(You had better) …': 'Вам лучше …',
			'Well..': 'Ну…',
			'So…': 'Так \ итак',
			'As for me': 'Что касается меня',
			'As far as I remember…': 'Насколько я помню…',
			'As far as I know…': 'Насколько я знаю…',
			'Actually…': 'Вообще-то',
			'By the way': 'Кстати',
			'The problem is that': 'Проблема в том, что…',
			'The point is that': 'Суть в том, что',
			'On the one hand…,\non the other hand…': 'С одной стороны…\nс другой стороны…',
			'Fortunately…': 'К счастью…',
			'Unfortunately…': 'К сожалению…',
			'In my opinion…': 'По моему мнению…',
			'It seems to me that…': 'Мне кажется…',
			'I think \ I guess': 'Я думаю…',
			'Personally, I suppose …': 'Лично я считаю…',
			'Moreover, …': 'Более того, …',
			'What’s worse is that': 'Что хуже',
			'Briefly speaking …': 'Короче говоря…',
			'Be careful': 'Будь осторожен',
			'Be careful driving': 'Будь осторожен за рулем',
			'Can you translate\nthis for me?': 'Ты не мог бы\nперевести это для меня?',
			'Chicago is very\ndifferent from Boston': 'Чикаго очень\nотличается от Бостона',
			'Don`t worry': 'Не беспокойтесь',
			'Everyone knows it': 'Все знают это',
			'Everything is ready': 'Всё готово',
			'Excellent': 'Отлично',
			'From time to time': 'Время от времени',
			'Good idea': 'Хорошая идея',
			'He likes it very much': 'Ему это очень нравится',
			'Help!': 'Помогите!',
			'He`s coming soon': 'Он скоро приезжает\n(приходит)',
			'He`s right': 'Он прав',
			'He`s very annoying': 'Он очень раздражающий',
			'He`s very famous': 'Он очень знаменит',
			'How are you?': 'Как твои дела?',
			'How`s work going?': 'Как идёт работа?',
			'Hurry!': 'Поторопись!',
			'I ate already': 'Я уже поел',
			'I can`t hear you': 'Я не слыщу тебя',
			'I`d like to go\nfor a walk': 'Я хотел бы прогуляться\n(пройтись пешком)',
			'I don`t know how\nto use it': 'Я не знаю, как\nэто использовать',
			'I don`t like him': 'Он мне не нравится',
			'I don`t like it': 'Мне это не нравится',
			'I don`t speak very well': 'Я не очень\nхорошо разговариваю',
			'I don`t understand': 'Я не понимаю',
			'I don`t want it': 'Я не хочу это',
			'I don`t want that': 'Я не хочу то',
			'I don`t want to bother you': 'Я не хочу\nтебя беспокоить',
			'I feel good': 'Я хорошо себя чувствую',
			'If you need my help,\nplease let me know': 'Если тебе нужна моя\nпомощь, пожалуйста,\nдай мне знать',
			'I get off of work at 6': 'Я покинул рабочее\nместо в 6',
			'I have a headache': 'У меня головная боль',
			'I hope you and your\nwife have a nice trip': 'Я надеюсь, у тебя\nи твоей жены будет\nхорошая поездка',
			'I know': 'Я знаю',
			'I like her': 'Она мне нравится',
			'I`ll call you when\nI leave': 'Я позвоню тебе,\nкогда буду уезжать',
			'I`ll come back later': 'Я приду назад позже',
			'I`ll take it': 'Я возьму это',
			'I`ll take you to the\nbus stop': 'Я довезу тебя\nдо автобусной остановки',
			'I`ll pay': 'Я заплачу',
			'I lost my watch': 'Я потерял свои часы',
			'I love you': 'Я люблю тебя',
			'I`m an American': 'Я американец',
			'I`m cleaning my room': 'Я навожу порядок\nв своей комнате',
			'I`m cold': 'Мне холодно',
			'I`m coming to pick you up': 'Я иду захватить тебя',
			'I`m going to leave': 'Я ухожу',
			'I`m good, and you?': 'Я хорошо, а ты?',
			'I`m happy': 'Я счастлив',
			'I`m hungry': 'Я голоден',
			'I`m married': 'Я женат',
			'I`m not busy': 'Я не занят',
			'I`m not married': 'Я не женат',
			'I`m not ready yet': 'Я еще не готов',
			'I`m not sure': 'Я не уверен',
			'I`m sorry, we`re\nsold out': 'Извиняюсь,\nмы все распродали',
			'I`m thirsty': 'У меня жажда',
			'I`m very busy. I\ndon`t have time now': 'Я очень занят. У\nменя сейчас нет времени',
			'I need to change clothes': 'Мне нужно сменить одежду',
			'I need to go home': 'Мне нужно идти домой',
			'I only want a snack': 'Я хочу только\nлёгкую закуску',
			'Is Mr. Smith an American?': 'Мистер Смит американец?',
			'Is that enough?': 'Этого достаточно?',
			'I think it`s very good': 'Я думаю, что очень хорошо',
			'I think it tastes good': 'Я думаю, это очень вкусно.',
			'I thought the clothes\nwere cheaper': 'Я думал, что\nодежда была дешевле',
			'It`s longer than 2 miles': 'Это больше, чем 2 мили',
			'I`ve been here for\ntwo days': 'Я здесь 2 дня.',
			'I`ve heard Texas\nis a beautiful place': 'Я слышал, что\nТехас - красивое место',
			'I`ve never seen\nthat before': 'Я никогда этого раньше не видел',
			'I was about to leave the restaurant when my friends arrived': 'Я собирался покинуть\nресторан, когда\nпришли мои друзья',
			'Just a little': 'Немного',
			'Just a moment': 'Один момент',
			'Let me check': 'Позвольте мне проверить',
			'Let me think about it': 'Позвольте мне\nподумать об этом',
			'Let`s go have a look': 'Давайте пойдем, посмотрим',
			'Let`s practice English': 'Давайте попрактикуем\nанглийский',
			'May I speak to Mrs.\nSmith please?': 'Можно поговорить с\nМиссис Смит, пожалуйста?',
			'More than that': 'Больше чем это.',
			'Never mind': 'Ничего страшного',
			'Next time': 'В следующий раз',
			'No': 'Нет',
			'Nonsense': 'Абсурд',
			'No, thank you': 'Нет, спасибо',
			'Nothing else': 'Больше ничего',
			'Not recently': 'Не недавно',
			'Not yet': 'Еще нет',
			'Of course': 'Конечно',
			'Okay': 'Хорошо',
			'Please fill out this form': 'Пожалуйста, заполните\nэту форму',
			'Please take me to this\naddress': 'Пожалуйста, довезите\nменя до этого адреса',
			'Please write it down': 'Пожалуйста, запишите это',
			'Really?': 'Действительно?',
			'Right here': 'Прямо здесь',
			'Right there': 'Прямо там',
			'See you later': 'До скорого',
			'See you tomorrow': 'До завтра',
			'See you tonight': 'Увидимся сегодня вечером',
			'She`s pretty': 'Она симпотичная',
			'Sorry to bother you': 'Извини, что помешал тебе',
			'Stop!': 'Остановитесь',
			'Take a chance': 'Воспользуйся шансом',
			'Take it outside': 'Вынеси это на улицу',
			'Tell me': 'Скажи мне',
			'Thanks for everything': 'Спасибо за все',
			'Thanks for your help': 'Спасибо за вашу помощь',
			'Thank you': 'Спасибо',
			'Thank you miss': 'Спасибо, мисс',
			'Thank you sir': 'Спасибо, сэр',
			'Thank you very much': 'Спасибо большое',
			'That looks great': 'Это выглядит превосходно',
			'That`s alright': 'Все в порядке',
			'That`s enough': 'Этого достаточно',
			'That`s fine': 'Это нормально',
			'That`s it': 'Вот и все',
			'That smells bad': 'Это плохо пахнет',
			'That`s not fair': 'Это несправедливо',
			'That`s not right': 'Это неправильно',
			'That`s right': 'Это правильно',
			'That`s too bad': 'Это очень плохо',
			'That`s too many': 'Это очень много',
			'That`s too much': 'Это очень много',
			'The book is under the table': 'Книга под столом',
			'They`ll be right back': 'Они скоро вернуться',
			'They`re the same': 'Они одинаковые',
			'They`re very busy': 'Они очень заняты',
			'This doesn`t work': 'Это не работает',
			'This is very difficult': 'Это очень тяжело',
			'This is very important': 'Это очень важно',
			'Try it': 'Попробуй это',
			'Very good, thanks': 'Очень хорошо, спасибо',
			'We like it very much': 'Нам это очень нравится',
			'Would you take a\nmessage please?': 'Не могли бы вы\nполучить сообщение?',
			'Yes, really': 'Да, действительно',
			'You`re beautiful': 'Ты красивая',
			'You`re very nice': 'Ты очень милая',
			'You`re very smart': 'Ты очень умный',
			'Your things are\nall here': 'Все твои вещи здесь',
			'Certainly!': 'Конечно!',
			'Good afternoon': 'Добрый день',
			'Good evening sir': 'Добрый вечер, сэр',
			'Good Luck': 'Удачи',
			'Good morning': 'Доброе утро',
			'Great': 'Превосходно',
			'Happy Birthday': 'С днем рождения',
			'Have a good trip': 'Хорошей поездки',
			'Nice to meet you': 'Приятно с тобой познакомиться'}





spis = []



class Container(GridLayout):


	label2_widget = ObjectProperty()
	label_widget = ObjectProperty()

	def change_text(self):
		self.label2_widget.text = ''
		try:
		    self.label_widget.text = random.choice(phraseslovar)
		    spis.append(self.label_widget.text)
		except:
		    self.label_widget.text = 'Вы исключили все фразы!\nДля повторения перезапустите приложение.'


	def change_text2(self):
		if spis == []:
			self.label2_widget.text = ''
		else:
			self.label2_widget.text = dict500[spis[-1]]

	def fuck_kley(self):
	        try:
	            if spis[-1] in phraseslovar:
	                phraseslovar.remove(spis[-1])
	        except:
	            self.label_widget.text = 'Пока нет фраз для исключения.\nЖмите "Следующая"'

		
		

class MyApp(App):
	def build(self):

		return Container()


if __name__=='__main__':
	MyApp().run()
